Fix filename of
noalien/GL4Dummies pull request #19
Opened 2020-10-24 15:36 UTC by fiplox

Following the issue #10 I rewrote your function filenameOf using strrch().

2020-10-24 16:25 UTC, darnuria requested changes

2020-10-24 16:25 UTC, darnuria commented on lib_src/GL4D/gl4dummies.c
> +  tmp++;
Alors la se pause une question intérressante @noalien avait pensé une API avec Malloc genre comme si on renvoyais un `String` en Rust. Toi tu pense comme si tu renvoyais un `&str`.

Fondamentalement ton approche est un peu aggressive certes elle va clore aussi #9, mais êtes l'api que @noalien avait pensé ? Une API ou on `clone` le filename en somme et ou il faut le `free`?

Si @noalien est d'accord pour intégré tu devrat ensuite corriger la doc! Et vérifier que ça casse aucun code et on devra incrémenter le numéro de version de la lib majeur car on a cassé le contrat et du vieux code des utilisateurs va plus s'executer sans crash! :)

Donc une version moins aggresive c'est de garder le cloning mais pourquoi pas en utilisant de façon maline [strndup](https://pubs.opengroup.org/onlinepubs/9699919799/) de POSIX.1-2008. ;)

2020-10-24 18:28 UTC, fiplox commented on lib_src/GL4D/gl4dummies.c
> +  tmp++;
j'ai commité un changement pour return `strdup()` de `tmp` pour pouvoir le `free()` apres.

2020-10-24 20:10 UTC, darnuria requested changes

2020-10-24 20:10 UTC, darnuria commented on lib_src/GL4D/gl4dummies.c
>    assert(tmp);
Moi je bougerais le `assert` plus bas après le `strdup` :)

2020-10-24 20:10 UTC, darnuria commented on lib_src/GL4D/gl4dummies.c
> +  return strdup(tmp);
Genre ici `assert(tmp)` car si `tmp` est `null` `strdup` renvera `null`

2020-10-24 20:12 UTC, fiplox commented on lib_src/GL4D/gl4dummies.c
>    assert(tmp);
j'avais du voir ca. Merci!

2020-10-24 21:22 UTC, darnuria requested changes

2020-10-24 21:22 UTC, darnuria commented on lib_src/GL4D/gl4dummies.c
> +  char *tmp = strrchr(path, '/');
Détail fares (et moi dans mes codes C) a l'habitude d'écrire `type * identifier` peut-tu respecter cette convention comme j'ai vu qui est appliqué dans cette lib? :)

2020-10-27 09:54 UTC, darnuria commented
@fiplox update? Si tu es bon je test en local si c'est bon je ping fares et go review :)

2020-10-27 10:05 UTC, fiplox commented
@darnuria Normalement, la version actuelle devrait bien marcher. 

Pour le deuxieme point je vais regarder et au cas ou ouvrir un deuxieme PR.

2021-02-04 10:38 UTC, noalien commented
char *tmp = strrchr(path, '/'); n'est pas équivalent au résultat attendu. Si path est vide (juste un '\0') ou path contenait un nom sans présence de '/' une duplication de son contenu (même vide) est renvoyée.

2021-02-07 22:11 UTC, darnuria requested changes

2021-02-07 22:11 UTC, darnuria commented on lib_src/GL4D/gl4dummies.c
> +  return strdup(tmp);
Tu a vu passé ce bout de la review? :) Moi ça me va mais faut updater la doc pour dire que la fonction peut retourner NULL si elle echoue et donc pousser le caller a faire un usage de assert! :O

genre avec un exemple de code dans la doc

2021-02-07 22:11 UTC, darnuria commented on lib_src/GL4D/gl4dummies.c
> +  return strdup(tmp);
Pour prendre en compte la remarque de @noalien un if qui check le retour du `strrchr` peut aider et alloue pour conserver l'API voulue. (peut-être aussi ajouter les retours de @noalien dans la doc! :)

2021-02-11 08:14 UTC, fiplox commented on lib_src/GL4D/gl4dummies.c
> +  return strdup(tmp);
le retour de `strrchr` d'une path vide renvoi `null`. Du coup, j'ai rajouté un test sur le `path`

2021-02-12 11:19 UTC, noalien commented
Attention : le comportement de filenameOf("chaine sans slash") ne me paraît pas préservé.

2021-08-06 13:40 UTC, fiplox commented
Désolé pour cet immense délai. Cette fois le comportement doit être bon. L'avantage de cette version est seulement la lisibilité

2022-01-31 09:43 UTC, fiplox commented
ping :)

2022-01-31 09:59 UTC, merged

2022-12-12 11:27 UTC, neilbel commented on lib_src/GL4D/gl4dummies.c
> +  if (*path == '\0' || tmp == NULL)
le *path == '\0' n'est pas utile

2022-12-12 11:31 UTC, noalien commented on lib_src/GL4D/gl4dummies.c
>    assert(tmp);
assert(tmp); n'est pas nécessaire non plus

2022-12-12 11:32 UTC, noalien commented on lib_src/GL4D/gl4dummies.c
> +  tmp++;
on peut le faire en pré-incrément sur le dernière ligne " return strdup(++tmp); "

2022-12-12 11:36 UTC, noalien commented
au final la fonction peut se réduire à :
```
char * filenameOf(const char * path) {
  char * tmp = strrchr(path, '/');
  if (tmp == NULL)
    return strdup(path);
  return strdup(++tmp);
}

```

2022-12-17 14:19 UTC, darnuria commented
J'irais meme jusque a dire autant faire un `strlen` et ensuite utiliser `memchr` et `strndup` \o/