Fix_Issue_#16 Essai N*2
noalien/GL4Dummies pull request #25
Opened 2020-10-25 02:15 UTC by Bibi210

Re-bonjour voici donc ma modification pour résoudre l'issue #16

2020-10-25 13:43 UTC, darnuria requested changes

2020-10-25 13:43 UTC, darnuria commented on configure.ac
> +CFLAGS="-Wall -Wextra -O3"
C'est bien maintenant pense a donner un bon titre à ton commit. :)

Comme `Fix #16 ajout -Wextra dans CFLAGS` en français ou anglais selon les anciens commits que tu pourra voir avec `git log`.

2020-10-25 22:41 UTC, Bibi210 commented
Alors en effectuant un recherche via rgrep sur les assert dans le code de la GL4Dummies je suis tombé sur deux façon de faire
"malloc(x)           "malloc(x)"
<<CODE>> OU  "assert(x)"
assert(x)"           <<CODE>>
Or si j'applique la deuxième syntaxe sur le fichier cela permet de régler l'issue #13 et l'issue #21

2020-10-26 07:29 UTC, darnuria commented
> Je propose donc un commit qui applique cette syntaxe sur tout le fichier list.c afin de garder de la cohérence

C'est pas un *soucis de syntaxe*, c'est un *problème de semantique*.

`malloc` peut échouer c'est rare, mais étant donné que la GL4Dummies est une lib pédagogique on préférera un crash propre avec un véritable message qui indique quelle ligne échoue le `assert` qui vérifie que le pointeur est pas `NULL`

Extrait du `man` de `malloc` sous linux:

> RETURN VALUE
>       The  `malloc()`  and `calloc()` functions return a pointer to the allocated
>       memory, which is suitably aligned for any  built-in  type.   On  error,
>       these functions return NULL.  NULL may also be returned by a successful
>       call to `malloc()` with a size of zero, or by a successful call  to  cal‐
>       `loc()` with nmemb or size equal to zero.

En Rust on aurait retourné `Option<T>` ou `Result<T, E>` pour obliger l'appellant (toi le dev) qui utilise la lib a vérifier la valeur de retour. En C on a la "liberté" d'introduire une faille de sécurité/fiabilité.

Dans le vrai monde on  aurais repris l'API pour avoir une valeur d'erreur mais la c'est bien le `assert`.

2020-10-26 07:42 UTC, darnuria reviewed
Je te laisse apprecier le message que j'ai laissé sur pourquoi c'est un soucis de semantique et non de syntaxe (pas la même chose! c'est comme les fautes d'orthographe, de grammaire et de sens pas la même tasse de thé!)

2020-10-26 07:43 UTC, darnuria approved these changes
Mais c'est bon pour moi sinon. @noalien je pense que tu peux review celle la!

2020-10-26 08:30 UTC, noalien approved these changes
Merci pour ces corrections ! Je valide.

2020-10-26 08:30 UTC, merged